version: '3.9'
services:
  antink-server:
    build: ./antink-server
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./it24_host:/original
      - ./antink_mount:/mnt/fuse
      - ./antink-logs:/logs

  antink-logger:
    build: ./antink-logger
    volumes:
      - ./antink-logs:/logs
